tif/kudos/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from . import views

urlpatterns = [
	path('', views.dashboard, name='dashboard'),
	path('profile/', views.profile, name='profile'),
	path('login/', views.login, name='login')
	
]

urlpatterns += staticfiles_urlpatterns()

tif/tif/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('kudos.urls')),
    path('admin/', admin.site.urls),
]

tif/kudos/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser

# https://learndjango.com/tutorials/django-custom-user-model

class CustomUser(AbstractUser):
	# user info
	name = models.CharField(max_length = 50)
	organisation = models.IntegerField(default = 0)
	email = models.CharField(max_length = 40)

	# user statistics
	kudosSent = models.IntegerField(default = 0)
	kudosReceived = models.IntegerField(default = 0)
	starsReceived = models.IntegerField(default = 0)
	prizeCount = models.IntegerField(default = 0)

	def __str__(self):
		return str(self.organisation) + " - " + self.name 

class Organisation(models.Model):
	name = models.CharField(max_length = 50)
	def __str__(self):
		return self.name

class Kudos(models.Model):
	date = models.DateField(default = datetime.date.today)
	sender = models.IntegerField(default = 0)
	message = models.CharField(max_length = 100, default="")
	recipient = models.IntegerField(default = 0)
	organisation = models.IntegerField(default = 0)

	def __str__(self):
		return self.id

class Prize(models.Model):
	date = models.DateField(default = datetime.date.today)
	description = models.CharField(max_length = 100)

	def __str__(self):
		return self.description

tif/kudos/forms.py
from django import forms
from .models import CustomUser
from django.forms.widgets import HiddenInput
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class UpdatePrizeForm(forms.Form):
    prize_description = forms.CharField(label="Prize:", max_length=100)

    def clean_prize(self):
        data = self.cleaned_data['prize_description']
        return data

class SendKudoForm(forms.Form):
    NAME_CHOICES = [(int(user.id), user.name) for user in CustomUser.objects.all()]
    recipient = forms.IntegerField(label="Recipient:", widget=forms.Select(choices=NAME_CHOICES))
    message = forms.CharField(label="Message:", max_length=100)
    
    def clean_message(self):
        data = self.cleaned_data['message']
        return data
    def clean_recipient(self):
        data = self.cleaned_data['recipient']
        return data
    
class RateKudoStars(forms.Form):
    RATING_CHOICES = [(i, i) for i in range(1, 6)]
    id = forms.IntegerField(widget=HiddenInput())
    rating = forms.IntegerField(label="Rating:", widget=forms.Select(choices=RATING_CHOICES))
    def clean_id(self):
        data = self.cleaned_data['id']
        return data
    def clean_rating(self):
        data = self.cleaned_data['rating']
        if data < 1 or data > 5:
            return 3
        else:
            return data

tif/kudos/views.py
from datetime import datetime
from django.shortcuts import render
from django.core.checks import messages
from django.http import HttpResponse, request
from django.http.response import HttpResponseRedirect
from .models import CustomUser, Organisation, Prize, Kudos
from .forms import UpdatePrizeForm, SendKudoForm, RateKudoStars

def login(request):
	return render(request, "login.html")

def dashboard(request):
	# if not request.user.is_authenticated():
	# 	return render(request, "login.html")
	
	user = CustomUser.objects.get(name="Matthew")
	# change to user = request.user later on
	organisation = Organisation(name="My Organisation")
	
	is_organisation = False # change to check whether user is admin in the future
	
	user_context = {
		"users": CustomUser.objects.order_by('-starsReceived')[:3],
		"name": user.name,
		"kudosSent": user.kudosSent,
		"kudosReceived": user.kudosReceived,
		"starsReceived": user.starsReceived,
		"ranking": CustomUser.objects.filter(starsReceived__gt=user.starsReceived).count() + 1,
		"currentPrize": "N/A" if not len(Prize.objects.all()) else Prize.objects.all()[0],
	}
	
	org_context = {
		"name": organisation.name,
		"currentPrize": "N/A" if not len(Prize.objects.all()) else Prize.objects.all()[0],
	}

	if is_organisation:
		return render(request, "organization/index.html", org_context)
	return render(request, "user/index.html", user_context)

def profile(request):
	# if not request.user.isAuthenticated:
	#	return render(request, "login.html")
	
	user = CustomUser.objects.get(name="Matthew")
	organisation = Organisation(name="My Organisation")
	# change to user = request.user later on

	is_organisation = False # change to check whether user is admin in the future

	if request.method == 'POST':
		if is_organisation:
			form = UpdatePrizeForm(request.POST)
			if form.is_valid():
				new_description = form.cleaned_data['prize_description']
				if len(Prize.objects.all()):
					current_prize = Prize.objects.all()[0]
					current_prize.description = new_description
				else:
					current_prize = Prize(description=new_description)
				current_prize.save()
				return HttpResponseRedirect('/')
		else:
			if "sendKudos" in request.POST:
				form = SendKudoForm(request.POST)
				if form.is_valid():
					# add a new kudo to the database
					message = form.cleaned_data['message']
					recipient = form.cleaned_data['recipient']
					new_kudos = Kudos(message=message, sender=user.id, recipient=recipient)
					new_kudos.save()
					# increment kudos sent for user
					user.kudosSent += 1
					user.save()
					# increment kudos received by recepient
					recipientUser = CustomUser.objects.get(id=recipient)
					recipientUser.kudosReceived += 1
					recipientUser.save()
			else:
				form = RateKudoStars(request.POST)
				if form.is_valid():
					kudoId = form.cleaned_data['id']
					rating = form.cleaned_data['rating']
					print(kudoId, rating)
					currentKudo = Kudos.objects.get(id=kudoId)
					# give rating to recipient
					recipient = currentKudo.recipient
					recipientUser = CustomUser.objects.get(id=recipient)
					recipientUser.starsReceived += rating
					recipientUser.save()
					# remove kudo from database
					currentKudo.delete()
			return HttpResponseRedirect('/profile')
			
	else:
		# create default forms for get request
		send_kudos_form = SendKudoForm()
		rate_kudos_form = RateKudoStars()
		prize_form = UpdatePrizeForm()

	user_context = {
		"name": user.name,
		"rank": CustomUser.objects.filter(starsReceived__gt=user.starsReceived).count() + 1,
		"prizeCount": user.prizeCount,
		"users": CustomUser.objects.all(),
		"kudos": Kudos.objects.filter(recipient=user.id),
		"sendKudosForm": send_kudos_form,
		"rateKudosForm": rate_kudos_form,
	}

	org_context = {
		"name": organisation.name,
		"prize": "N/A" if not len(Prize.objects.all()) else Prize.objects.all()[0],
		"form": prize_form,
	}

	if is_organisation:
		return render(request, "organization/profile.html", org_context)
	return render(request, "user/profile.html", user_context)

tif/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kudos Corner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

    <div id="main-content">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

tif/templates/login.html
{% extends 'base.html' %}

{% block content %}
    
    <div id="login-form">
        <form action="#" id="login" method="GET">
            <label for="username">Username</label>
            <input type="text" class="form-control" value="" id="username">
            <label for="password">Password</label>
            <input type="password" class="form-control" value="" id="password">
        </form>
        <button class="btn btn-primary submit-login submit">Log in</button>
    </div>
        
{% endblock content %}

tif/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand logo-name" href="#">Kudos Korner</a>
        {% load static %} <img class="logo" width="40px" src="{% static 'media/kudos_korner_icon_final.png' %}" alt="home" />
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
                <a class="nav-link" href="/profile">Profile</a>
                <a class="nav-link" href="/login">Log In</a>
            </div>
        </div>
    </div>
  </nav>

tif/templates/organization/index.html
{% extends 'base.html' %}

{% block content %}

    <h1>Welcome to Kudos Corner, {{ name }}</h1>

    <div id="prize">
        <p>This week's prize is {{ currentPrize }} </p>
    </div>

{% endblock content %}

tif/templates/organization/profile.html
{% extends 'base.html' %}

{% block content %}

    <div id="update-prize">
        <h1>{{ name }}</h1>
        <p>Current prize: {{ prize }}</p>
        
        <form action="/profile/" method="POST">
            {% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
            <button class="btn btn-primary submit submit-login" type="submit">Update</button>
        </form>
    </div>
    
{% endblock content %}

tif/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    
    <div id="signup-form">
        <form action="#" id="signup" method="POST">
            <label for="username">Username</label>
            <input type="text" class="form-control" value="" id="username">
            <label for="password">Password</label>
            <input type="password" class="form-control" value="" id="password">
        </form>
        <button class="btn btn-primary submit-login submit">Sign up</button>
    </div>
        
{% endblock content %}

tif/templates/user/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="leaderboard">
            <h2>Leaderboard</h2>
            
            <!-- <p>Personal Rank: {{ ranking }}</p> -->
            <table id="leaderboard-table">
                <thead>
                    <tr>
                        <td>Rank</td>
                        <td>Name</td>
                        <td>Stars</td>
                    </tr>
                </thead>
                {% for user in users %}
                    <tr class="{% if user.name == name %}chosen-row{% endif %}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.starsReceived }}</td>
                    </tr>
                {% endfor %}
                {% if ranking > 3 %}
                    <tr>
                        <td>⋮</td>
                        <td>⋮</td>
                        <td>⋮</td>
                    </tr>
                    <tr class="chosen-row">
                        <td>{{ ranking }}</td>
                        <td>{{ name }}</td>
                        <td>{{ starsReceived }}</td>
                    </tr>
                {% endif %}
            </table>
        </div>

        <div class="prize">
            <h3>This week's prize </h3>
            <h4 style="background-color: #D2FDFF">{{ currentPrize }} </h4>
        </div>

        <div class="kudos">
            <div id="sent"><h2>{{ kudosSent }}</h2> sent</div>
            <div id="received"><h2>{{ kudosReceived }}</h2> received</div>
            <div id="stars"><h2>{{ starsReceived }}</h2> stars</div>
        </div>
    </div>


    
{% endblock content %}

tif/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="wrapper">
    <div id="stats">
        <h2>{{ name }}'s Stats</h2>
        <h4>Current ranking: {{ rank }}</h4>
        <h4>Prizes won: {{ prizeCount }}</h4>
    </div> 

    <div id="rate-kudos">
        <h2>Kudos Inbox {% if kudos %} - {{ kudos|length }} unread {% endif %}</h2>
            <div class="inbox">
            {% for kudo in kudos %}
                <div class="message">
                    <div class="message-entry">> {{kudo.message}}</div>
                    <form action ="" method="POST">
                        {% csrf_token %}
                        <button type="submit" name="rateKudos" class="btn btn-primary submit">Rate</button>
                        {% for field in rateKudosForm %}
                            {% if field.is_hidden %}
                                <input type="number" hidden="true" name="id" required="" id="id_id" value={{kudo.id}}>
                            {% else %}
                                {{ rateKudosForm.rating }}
                            {% endif %}
                        {% endfor %}
                        {% load static %} <img width="30px" src="{% static 'media/star-icon.png' %}" alt="home" />
                    </form>
                </div>
            {% endfor %}
            </div>
    </div>
    
    <div id="send-kudos">
        <h2 style="text-align: center;">Send Kudos</h2>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ sendKudosForm.as_table}}
            </table>
            <button type="submit" name="sendKudos" class="btn btn-primary submit send">Send</button>
        </form>
    </div>

</div>

    
{% endblock content %}